use ak_a
SELECT * FROM [dbo].[Customer]
SELECT * FROM [dbo].[prod_cat_info]
SELECT * FROM [dbo].[Transactions]

--DATA PREPARATION AND UNDERSTANDING

/*1. What is the total number of rows in each of the 3 tables in the database?  */
select count(*) as total_rows from Customer 
select count(*) as total_rows from prod_cat_info
select count(*) as total_rows from Transactions

/*2. What is the total number of transactions that have a return? */
select count(distinct transaction_id) as return_transactions
from Transactions
where total_amt<0

/*3. As you would have noticed, the dates provided across the datasets are not in a
correct format. As first steps, pls convert the date variables into valid date formats
before proceeding ahead. */
SELECT 
CONVERT(DATE,DOB,105) FROM Customer

SELECT 
CONVERT(DATE,tran_date,105)FROM Transactions



/*4. What is the time range of the transaction data available for analysis? Show the
output in number of days, months and years simultaneously in different columns. */
select datediff(DAY,min(tran_date),max(tran_date)) as Total_days,
       datediff(month,min(tran_date),max(tran_date))as Total_months,
	   datediff(year,min(tran_date),max(tran_date))as Total_years

from Transactions


5.
/*5. Which product category does the sub-category “DIY” belong to? */
SELECT prod_cat
from prod_cat_info
where prod_subcat='DIY'


--DATA ANALYSIS
1.
/*1. Which channel is most frequently used for transactions? */
SELECT Store_type, COUNT(*) AS TOTAL_TRANSACTIONS
from Transactions
GROUP BY Store_type
order by count(*) desc

2.
/*2. What is the count of Male and Female customers in the database? */
select GENDER, COUNT(*) FROM Customer
GROUP BY Gender

3
/*3. From which city do we have the maximum number of customers and how many? */
SELECT CITY_CODE, COUNT(*)
FROM Customer
GROUP BY CITY_CODE
ORDER BY COUNT(*) DESC

4.
/*4. How many sub-categories are there under the Books category? */
SELECT COUNT(PROD_CAT)
FROM prod_cat_info
WHERE PROD_CAT='BOOKS'

5.
/*5. What is the maximum quantity of products ever ordered? */
SELECT prod_cat_code,MAX(QTY) as quantity
FROM Transactions
group by prod_cat_code

select * from prod_cat_info

6
/*6. What is the net total revenue generated in categories Electronics and Books? */
select p.prod_cat ,sum(t.total_amt) as total_revenue
from prod_cat_info as p
join Transactions as t
on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
where p.prod_cat in ('Electronics','Books')
group by p.prod_cat

7.
/*7. How many customers have >10 transactions with us, excluding returns? */
select cust_id, count(transaction_id) from Transactions
where Qty>0
group by cust_id
having count(transaction_id)>10
order by count(*) desc

8.
/*8. What is the combined revenue earned from the “Electronics” & “Clothing”
categories, from “Flagship stores”? */
select p.prod_cat,Store_type,sum(total_amt) as total_revenue
from prod_cat_info as p
join Transactions as t
on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
where Store_type='Flagship store' and p.prod_cat in ('Electronics','Clothing')
group by p.prod_cat,Store_type

9.
/*9. What is the total revenue generated from “Male” customers in “Electronics”
category? Output should display total revenue by prod sub-cat. */
select p.prod_subcat,sum(total_amt) as total_revenue
from customer as c
join Transactions as t
on c.customer_Id= t.cust_id
join prod_cat_info as p
on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where Gender='M' and p.prod_cat='Electronics'
group by p.prod_subcat

10.
/*10. What is percentage of sales and returns by product sub category; display only top
5 sub categories in terms of sales? */
select * from 
(select top 5 prod_subcat, (sum(total_amt)/(select sum(total_amt) from Transactions))*100 as [% sales]
from prod_cat_info as p
join Transactions as t
on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
where total_amt>0
group by prod_subcat
order by [% sales] desc) as s1

join 

(select prod_subcat,(sum(total_amt)/(select sum(total_amt) from Transactions where total_amt<0))*100 as [% return]
from prod_cat_info as p
join Transactions as t
on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
where total_amt<0
group by prod_subcat) as s2

on s1.prod_subcat=s2.prod_subcat;


11.
/*11. For all customers aged between 25 to 35 years find what is the net total revenue
generated by these consumers in last 30 days of transactions from max transaction
date available in the data? */

select *
from 
( select Customer_id, datediff(year,DOB,max(convert(date,tran_date,205))) as age , sum(total_amt) as revenue from Transactions as t1
join Customer as t2 on t1.cust_id=t2.customer_Id
group by customer_Id,dob
having datediff(year,DOB,max(convert(date,tran_date,205))) between 25 and 35) as s1

join 
(
select * from (
select *,dateadd(day,-30,max_date) as cut_off from (
select cust_id,tran_date,max(convert(date,tran_date,105)) over() as max_date from Transactions
) as t3) as t4
where tran_date>cut_off) as s2
on s1.customer_Id=s2.cust_id

12.
/*12. Which product category has seen the max value of returns in the last 3 months of
transactions? */
select top 1 prod_cat 
from Transactions as t
join prod_cat_info as p
on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
WHERE tran_date >= ( select DATEADD(MONTH, -3,max(tran_date)) from Transactions) and qty<0 and total_amt<0
group by  prod_cat
order by sum(total_amt) 

13.
/*13. Which store-type sells the maximum products; by value of sales amount and by
quantity sold? */
select store_type,sum(qty)as _qty,sum(total_amt) as _amount
from Transactions
where total_amt>0 and qty>0
group by store_type
order by _amount desc,_qty desc

14.
/*14. What are the categories for which average revenue is above the overall average. */
select prod_cat ,avg(total_amt) as _avg
from prod_cat_info as p
join transactions as t 
on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
where total_amt>0
group by prod_cat
having avg(total_amt) >
(select avg(total_amt) 
from Transactions
where total_amt>0)



15. 
/*15. Find the average and total revenue by each subcategory for the categories which
are among top 5 categories in terms of quantity sold. */

select p.prod_subcat,avg(total_amt) as _avg, sum(total_amt) as _total
from Transactions as t
join  prod_cat_info as p on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where t.prod_cat_code IN ( 
   select top 5 prod_cat_code
   from transactions 
   where total_amt>0 and qty>0
   group by prod_cat_code
   order by sum(total_amt) desc
 )
group by p.prod_subcat    



















